// All
export const ALL = 'ALL'

// Guest
export const GUEST = 'GUEST'

// Admin
export const ADMIN = 'ADMIN'

// Seller
export const SELLER = 'SELLER'
export const SELLER_REGISTRATION_PENDING = 'SELLER_REGISTRATION_PENDING'
export const SELLER_LOCATION_UNAVAILABLE = 'SELLER_LOCATION_UNAVAILABLE'

// Buyer
export const BUYER = 'BUYER'
export const BUYER_SUBSCRIPTION_DELETED = 'BUYER_SUBSCRIPTION_DELETED'
export const BUYER_SUBSCRIPTION_CANCELLED = 'BUYER_SUBSCRIPTION_CANCELLED'
export const BUYER_INITIAL_PAYMENT_FAILED = 'BUYER_INITIAL_PAYMENT_FAILED'

// Misc
export const EMAIL_VERIFICATION_PENDING = 'EMAIL_VERIFICATION_PENDING'
