const roles = {
  ALL: 'ALL',
  GUEST: 'GUEST',
  ADMIN: 'ADMIN',
  SELLER: 'SELLER',
  SELLER_REGISTRATION_PENDING: 'SELLER_REGISTRATION_PENDING',
  SELLER_LOCATION_UNAVAILABLE: 'SELLER_LOCATION_UNAVAILABLE',
  BUYER: 'BUYER',
  BUYER_SUBSCRIPTION_DELETED: 'BUYER_SUBSCRIPTION_DELETED',
  BUYER_SUBSCRIPTION_CANCELLED: 'BUYER_SUBSCRIPTION_CANCELLED',
  BUYER_INITIAL_PAYMENT_FAILED: 'BUYER_INITIAL_PAYMENT_FAILED',
  EMAIL_VERIFICATION_PENDING: 'EMAIL_VERIFICATION_PENDING'
}

export const getRole = role => {
  if (!roles[role]) throw new Error(`Role ${role} does not exist`)
  return roles[role]
}
